const universities = [
  {
    campusName: "Cambodia Academy of Digital Technology",
    shortName: "CADT",
    type: "Public",
    websiteUrl: "https://www.cadt.edu.kh",
    logoUrl: "https://example.com/logos/cadt.png",
    coverImageUrl: "https://example.com/covers/cadt-campus.jpg",
    province: "Phnom Penh",
    city: "Phnom Penh",
    email: "info@cadt.edu.kh",
    phoneNumber: "+855-23-999-000",
    address: "St. 123, Phnom Penh",
    description: "CADT is a leading institution in digital technology education in Cambodia.",
    vision: "To be a center of excellence in digital innovation and entrepreneurship.",
    mission: "To provide cutting-edge education and research opportunities in the field of digital technology."
  },
  {
    campusName: "Royal University of Phnom Penh",
    shortName: "RUPP",
    type: "Public",
    websiteUrl: "http://www.rupp.edu.kh",
    logoUrl: "https://example.com/logos/rupp.png",
    coverImageUrl: "https://example.com/covers/rupp-campus.jpg",
    province: "Phnom Penh",
    city: "Phnom Penh",
    email: "info@rupp.edu.kh",
    phoneNumber: "+855-23-883-445",
    address: "Russian Federation Boulevard, Tuol Kouk, Phnom Penh",
    description: "The Royal University of Phnom Penh is the oldest and largest public university in Cambodia, established in 1960.",
    vision: "To become Cambodia's flagship university with regional and international recognition in teaching, research, and community service.",
    mission: "To build high-quality human resources with excellent knowledge, skills, and moral values to contribute to national development."
  },
  {
    campusName: "Institute of Technology of Cambodia",
    shortName: "ITC",
    type: "Public",
    websiteUrl: "https://www.itc.edu.kh",
    logoUrl: "https://example.com/logos/itc.png",
    coverImageUrl: "https://example.com/covers/itc-campus.jpg",
    province: "Phnom Penh",
    city: "Phnom Penh",
    email: "info@itc.edu.kh",
    phoneNumber: "+855-23-880-370",
    address: "Russian Federation Boulevard, Tuol Kouk, Phnom Penh",
    description: "ITC is a premier higher education institution in Cambodia specializing in engineering, technology, and sciences.",
    vision: "To be a leading university in science and technology recognized nationally, regionally, and internationally.",
    mission: "To provide high-quality education and research in engineering and technology to meet the socioeconomic needs of the country."
  },
  {
    campusName: "National University of Management",
    shortName: "NUM",
    type: "Public",
    websiteUrl: "https://www.num.edu.kh",
    logoUrl: "https://example.com/logos/num.png",
    coverImageUrl: "https://example.com/covers/num-campus.jpg",
    province: "Phnom Penh",
    city: "Phnom Penh",
    email: "info@num.edu.kh",
    phoneNumber: "+855-23-428-120",
    address: "Corner of Christopher Howes (St. 96) and Monivong Blvd, Daun Penh, Phnom Penh",
    description: "NUM is a leading public university in Cambodia recognized for its excellence in management, economics, and business education.",
    vision: "To be a premier university in entrepreneurship, innovation, and digital business leadership in the region.",
    mission: "To offer innovative academic programs that develop highly skilled professionals and entrepreneurs for the global market."
  },
  {
    campusName: "Zaman University (Paragon International University)",
    shortName: "ParagonIU",
    type: "Private",
    websiteUrl: "https://www.paragoniu.edu.kh",
    logoUrl: "https://example.com/logos/paragon.png",
    coverImageUrl: "https://example.com/covers/paragon-campus.jpg",
    province: "Phnom Penh",
    city: "Phnom Penh",
    email: "info@paragoniu.edu.kh",
    phoneNumber: "+855-23-996-111",
    address: "St. 315, Boeng Kak 1, Tuol Kouk, Phnom Penh",
    description: "Paragon International University is a leading private university in Cambodia offering international-standard education completely in English.",
    vision: "To become a center of excellence in teaching, research, and innovation in Southeast Asia.",
    mission: "To foster global citizens who think critically, innovate fearlessly, and lead ethically."
  },
  {
    campusName: "American University of Phnom Penh",
    shortName: "AUPP",
    type: "Private",
    websiteUrl: "https://www.aupp.edu.kh",
    logoUrl: "https://example.com/logos/aupp.png",
    coverImageUrl: "https://example.com/covers/aupp-campus.jpg",
    province: "Phnom Penh",
    city: "Phnom Penh",
    email: "info@aupp.edu.kh",
    phoneNumber: "+855-23-990-023",
    address: "St. 201R, Russey Keo, Phnom Penh",
    description: "AUPP is a private university offering rigorous, American-style dual degree higher education programs in Cambodia.",
    vision: "To be a center of academic excellence and a driving force for socioeconomic growth in Cambodia and ASEAN.",
    mission: "To provide a high-quality American-style education that empowers students to achieve career success and global competency."
  },
  {
    campusName: "Royal University of Law and Economics",
    shortName: "RULE",
    type: "Public",
    websiteUrl: "http://www.rule.edu.kh",
    logoUrl: "https://example.com/logos/rule.png",
    coverImageUrl: "https://example.com/covers/rule-campus.jpg",
    province: "Phnom Penh",
    city: "Phnom Penh",
    email: "contact@rule.edu.kh",
    phoneNumber: "+855-23-210-162",
    address: "Monivong Blvd, Chamkar Mon, Phnom Penh",
    description: "RULE is the first higher education institution in Cambodia specializing in legal and economic disciplines, founded in 1953.",
    vision: "To be a leading institution for legal, administrative, and economic education in Southeast Asia.",
    mission: "To produce competent professionals, researchers, and public servants equipped with deep legal and economic knowledge."
  },
  {
    campusName: "University of Cambodia",
    shortName: "UC",
    type: "Private",
    websiteUrl: "https://www.uc.edu.kh",
    logoUrl: "https://example.com/logos/uc.png",
    coverImageUrl: "https://example.com/covers/uc-campus.jpg",
    province: "Phnom Penh",
    city: "Phnom Penh",
    email: "info@uc.edu.kh",
    phoneNumber: "+855-23-993-274",
    address: "Northbridge Road, Sen Sok, Phnom Penh",
    description: "The University of Cambodia is a private higher education institution that aims to train leaders for tomorrow's Cambodia.",
    vision: "To prepare future generations of leaders to navigate an increasingly complex, globalized world.",
    mission: "To offer student-centered education that encourages critical thinking, cross-cultural understanding, and academic freedom."
  },
  {
    campusName: "Royal University of Agriculture",
    shortName: "RUA",
    type: "Public",
    websiteUrl: "http://www.rua.edu.kh",
    logoUrl: "https://example.com/logos/rua.png",
    coverImageUrl: "https://example.com/covers/rua-campus.jpg",
    province: "Phnom Penh",
    city: "Phnom Penh",
    email: "info@rua.edu.kh",
    phoneNumber: "+855-23-219-690",
    address: "St. 217, Dangkao, Phnom Penh",
    description: "RUA is the leading public agricultural university in Cambodia, overseeing vital research and development in the agricultural sector.",
    vision: "To be a leading agricultural institution recognized for excellence in human resources training and technology transfer.",
    mission: "To contribute to sustainable agricultural development and food security through education, research, and community outreach."
  },
  {
    campusName: "Paññāsāstra University of Cambodia",
    shortName: "PUC",
    type: "Private",
    websiteUrl: "http://www.puc.edu.kh",
    logoUrl: "https://example.com/logos/puc.png",
    coverImageUrl: "https://example.com/covers/puc-campus.jpg",
    province: "Phnom Penh",
    city: "Phnom Penh",
    email: "info@puc.edu.kh",
    phoneNumber: "+855-23-990-153",
    address: "Norodom Boulevard, Tonle Bassac, Chamkar Mon, Phnom Penh",
    description: "PUC is a private university offering English-based education with a strong emphasis on professional and ethical values.",
    vision: "To build an academic community that fosters peace, justice, and sustainable development.",
    mission: "To provide quality education accessible to all segments of society, preparing students for leadership in a changing world."
  },
  {
    campusName: "National University of Battambang",
    shortName: "NUBB",
    type: "Public",
    websiteUrl: "http://www.nubb.edu.kh",
    logoUrl: "https://example.com/logos/nubb.png",
    coverImageUrl: "https://example.com/covers/nubb-campus.jpg",
    province: "Battambang",
    city: "Battambang",
    email: "info@nubb.edu.kh",
    phoneNumber: "+855-53-952-905",
    address: "National Road 5, Sangkat Prek Preah Sdach, Battambang",
    description: "NUBB is a vital regional public university providing higher education opportunities in the northwest region of Cambodia.",
    vision: "To be a leading regional university driving sustainable rural development and agricultural innovation.",
    mission: "To offer quality local educational programs that respond directly to regional market demands and societal needs."
  }
];

export default universities;